spring:
  profiles:
    active: dev
security:
  oauth2:
    client:
      clientId: 1720871361566790
      clientSecret: d54eedee3225537ba7765d61e6c6524f
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
      auto-approve-scopes: false
    resource:
      userInfoUri: https://graph.facebook.com/me